"""Offline S0 fixtures, NOT a production proxy or resolver.

The mock upstream records requests but never connects to their destinations.
All names are reserved .example names; no credentials or internet are needed.
"""

import json
import socket
import socketserver
import ssl
import struct
import sys
import threading


def read_exact(stream, length):
    data = b""
    while len(data) < length:
        part = stream.read(length - len(data))
        if not part:
            raise EOFError("short fixture message")
        data += part
    return data


def questions(packet):
    """Decode the uncompressed questions generated by this fixture only."""
    count = struct.unpack("!H", packet[4:6])[0]
    offset, result = 12, []
    for _ in range(count):
        labels = []
        while packet[offset]:
            length = packet[offset]
            if length > 63:
                raise ValueError("compressed fixture question not supported")
            labels.append(packet[offset + 1:offset + 1 + length].decode("ascii"))
            offset += length + 1
        offset += 1
        qtype, qclass = struct.unpack("!HH", packet[offset:offset + 4])
        offset += 4
        result.append({"name": ".".join(labels), "type": qtype, "class": qclass})
    return result


def dns_packet(items):
    packet = struct.pack("!HHHHHH", 1234, 0x100, len(items), 0, 0, 0)
    for name, qclass in items:
        for label in name.split("."):
            packet += bytes([len(label)]) + label.encode("ascii")
        packet += b"\0" + struct.pack("!HH", 1, qclass)
    return packet


class MockProxy(socketserver.StreamRequestHandler):
    def handle(self):
        self.connection.settimeout(5)
        line = self.rfile.readline(4096)
        if not line:  # readiness probe
            return
        while self.rfile.readline(4096) not in (b"\r\n", b"\n", b""):
            pass
        print(json.dumps({"kind": "connect", "request": line.decode().strip()}), flush=True)
        # No outbound connection, even for allowed names.
        self.wfile.write(b"HTTP/1.1 200 Connection established\r\n\r\n")
        self.wfile.flush()
        data = self.rfile.read(1)
        if data == b"G":
            self.wfile.write(b"HTTP/1.1 200 OK\r\nContent-Length: 2\r\nConnection: close\r\n\r\nOK")
        # For HTTP/2 the CONNECT log, not a successful response, is the oracle.


class MockDNS(socketserver.StreamRequestHandler):
    def handle(self):
        self.connection.settimeout(5)
        header = self.rfile.read(2)
        if not header:
            return
        packet = read_exact(self.rfile, struct.unpack("!H", header)[0])
        print(json.dumps({"kind": "dns", "questions": questions(packet)}), flush=True)
        response = packet[:2] + b"\x81\x80" + packet[4:]
        self.wfile.write(struct.pack("!H", len(response)) + response)


class Server(socketserver.ThreadingTCPServer):
    allow_reuse_address = True
    daemon_threads = True

    def handle_error(self, request, client_address):
        print(json.dumps({"kind": "fixture_error"}), flush=True)


def serve():
    for port, handler in [(18080, MockProxy), (15353, MockDNS)]:
        server = Server(("0.0.0.0", port), handler)
        threading.Thread(target=server.serve_forever, daemon=True).start()
    print(json.dumps({"kind": "ready"}), flush=True)
    threading.Event().wait()


def frame(kind, flags, stream_id, payload):
    return len(payload).to_bytes(3, "big") + bytes([kind, flags]) + struct.pack("!I", stream_id) + payload


def probe(case, destination):
    if case == "capability":
        with socket.socket() as sock:
            try:
                sock.setsockopt(socket.SOL_SOCKET, 36, 114514)
            except PermissionError:
                print("SO_MARK denied")
                return
            raise AssertionError("SO_MARK unexpectedly permitted")
    if case.startswith("dns-"):
        items = {
            "dns-allow": [("allowed.example", 1)],
            "dns-deny": [("blocked.example", 1)],
            "dns-chaos": [("blocked.example", 3)],
            "dns-hesiod": [("blocked.example", 4)],
            "dns-any-class": [("blocked.example", 255)],
            "dns-multiple": [("allowed.example", 1), ("blocked.example", 1)],
            **{name: [("allowed.example", 1)] for name in (
                "dns-txt", "dns-answer", "dns-authority", "dns-extra", "dns-edns-payload")},
        }[case]
        packet = dns_packet(items)
        if case == "dns-txt":
            packet = packet[:-4] + struct.pack("!HH", 16, 1)
        if case in {"dns-answer", "dns-authority", "dns-extra", "dns-edns-payload"}:
            header = list(struct.unpack("!6H", packet[:12]))
            header[{"dns-answer": 3, "dns-authority": 4}.get(case, 5)] = 1
            payload = b"fixture-payload"
            if case == "dns-edns-payload":
                payload = struct.pack("!HH", 65001, len(payload)) + payload
                record = b"\0" + struct.pack("!HHIH", 41, 1232, 0, len(payload)) + payload
            else:
                payload = bytes([len(payload)]) + payload
                record = b"\x07blocked\x07example\0" + struct.pack("!HHIH", 16, 1, 0, len(payload)) + payload
            packet = struct.pack("!6H", *header) + packet[12:] + record
        with socket.create_connection(("127.0.0.1", 1053), timeout=4) as sock:
            sock.sendall(struct.pack("!H", len(packet)) + packet)
            print("DNS response bytes:", len(sock.recv(4096)))
        return
    host = "allowed.example" if case.endswith("allow") else "blocked.example"
    with socket.create_connection((destination, 443), timeout=4) as sock:
        if case.startswith("tls-"):
            context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
            context.check_hostname = False
            context.verify_mode = ssl.CERT_NONE  # offline mock has no TLS origin
            with context.wrap_socket(sock, server_hostname=None if case == "tls-no-sni" else host):
                pass
        elif case == "unknown-protocol":
            sock.sendall(b"\x01\x02\x03unsupported\r\n\r\n")
        elif case == "http-ip":
            sock.sendall(b"GET / HTTP/1.1\r\nHost: 127.0.0.1\r\n\r\n")
        elif case == "http-connect-mismatch":
            sock.sendall(b"CONNECT blocked.example:443 HTTP/1.1\r\nHost: allowed.example\r\n\r\n")
        elif case == "http-absolute-mismatch":
            sock.sendall(b"GET http://blocked.example/ HTTP/1.1\r\nHost: allowed.example\r\n\r\n")
        elif case.startswith("h2-"):
            # HPACK static GET, https, /; literal :authority without Huffman.
            if case == "h2-multiple":
                host = "allowed.example"
            headers = b"\x82\x87\x84\x01" + bytes([len(host)]) + host.encode()
            sock.sendall(b"PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n" + frame(4, 0, 0, b"") + frame(1, 5, 1, headers))
            if case == "h2-multiple":
                host = "blocked.example"
                headers = b"\x82\x87\x84\x01" + bytes([len(host)]) + host.encode()
                sock.sendall(frame(1, 5, 3, headers))
            # Do not close on the peer's initial SETTINGS before it has had an
            # opportunity to process our HEADERS and attempt the upstream dial.
            while sock.recv(4096):
                pass
        else:
            sock.sendall(f"GET / HTTP/1.1\r\nHost: {host}\r\nConnection: close\r\n\r\n".encode())
        print("response bytes:", len(sock.recv(1024)))


if __name__ == "__main__":
    if sys.argv[1] == "serve":
        serve()
    else:
        try:
            probe(sys.argv[1], sys.argv[2])
        except (TimeoutError, ConnectionError, EOFError, ssl.SSLError) as error:
            # Network failure is not a PASS. The runner inspects upstream logs.
            print(type(error).__name__)
