services:
  main:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - type: bind
        source: ../data
        target: /task/data
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ../models
        target: /task/models
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ./docs
        target: /task/docs
        read_only: true
        bind:
          create_host_path: false
